typography_spectrum: 0.16113747260533273
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.434048087336123
  lightness: 0.7180152083747089
  saturation: 0.7012177354190499
  rhythmicContrast: 0.15178096597082913
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2332
analytics:
  google: null
  facebook: null
  twitter: null
name: Apologetic Videos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Leibniz' Contingency Argument
    id: aa62b484-f6b5-416e-9530-9d830ccfa09a
    type: content
favicon: null
purpose: []
